name: Deploy to Bunny.net

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.4.5
        with:
          source: "dist"
          destination: ""
          storageZoneName: "asciibirdv3"
          storageEndpoint: "syd.storage.bunnycdn.com"
          storagePassword: "${{ secrets.BUNNY_STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.BUNNY_API_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_PULL_ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
          purgePullZoneDelay: "5"
          maxRetries: "5"
